# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drQt.ui'
#
# Created: Mon Jan 31 13:28:26 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 940)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.ST_main_ = QtGui.QSplitter(self.centralwidget)
        self.ST_main_.setOrientation(QtCore.Qt.Horizontal)
        self.ST_main_.setObjectName("ST_main_")
        self.TW_main = QtGui.QTabWidget(self.ST_main_)
        self.TW_main.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TW_main.sizePolicy().hasHeightForWidth())
        self.TW_main.setSizePolicy(sizePolicy)
        self.TW_main.setObjectName("TW_main")
        self.QW_job = QtGui.QWidget()
        self.QW_job.setObjectName("QW_job")
        self.gridLayout = QtGui.QGridLayout(self.QW_job)
        self.gridLayout.setObjectName("gridLayout")
        self.TW_job = QtGui.QTableWidget(self.QW_job)
        self.TW_job.setAutoFillBackground(False)
        self.TW_job.setAlternatingRowColors(True)
        self.TW_job.setObjectName("TW_job")
        self.TW_job.setColumnCount(0)
        self.TW_job.setRowCount(0)
        self.TW_job.horizontalHeader().setStretchLastSection(True)
        self.TW_job.verticalHeader().setCascadingSectionResizes(True)
        self.TW_job.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.TW_job, 0, 0, 1, 1)
        self.TW_main.addTab(self.QW_job, "")
        self.QW_node = QtGui.QWidget()
        self.QW_node.setObjectName("QW_node")
        self.gridLayout_2 = QtGui.QGridLayout(self.QW_node)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.TW_node = QtGui.QTableWidget(self.QW_node)
        self.TW_node.setObjectName("TW_node")
        self.TW_node.setColumnCount(0)
        self.TW_node.setRowCount(0)
        self.TW_node.horizontalHeader().setStretchLastSection(True)
        self.TW_node.verticalHeader().setCascadingSectionResizes(True)
        self.TW_node.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.TW_node, 0, 0, 1, 1)
        self.TW_main.addTab(self.QW_node, "")
        self.gridLayout_4.addWidget(self.ST_main_, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.PB_refresh = QtGui.QPushButton(self.centralwidget)
        self.PB_refresh.setDefault(False)
        self.PB_refresh.setFlat(False)
        self.PB_refresh.setObjectName("PB_refresh")
        self.horizontalLayout.addWidget(self.PB_refresh)
        self.CB_auto_refresh = QtGui.QCheckBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CB_auto_refresh.sizePolicy().hasHeightForWidth())
        self.CB_auto_refresh.setSizePolicy(sizePolicy)
        self.CB_auto_refresh.setObjectName("CB_auto_refresh")
        self.horizontalLayout.addWidget(self.CB_auto_refresh)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.SB_refresh_time = QtGui.QSpinBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SB_refresh_time.sizePolicy().hasHeightForWidth())
        self.SB_refresh_time.setSizePolicy(sizePolicy)
        self.SB_refresh_time.setObjectName("SB_refresh_time")
        self.horizontalLayout_2.addWidget(self.SB_refresh_time)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(81, 0))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.LB_header = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LB_header.sizePolicy().hasHeightForWidth())
        self.LB_header.setSizePolicy(sizePolicy)
        self.LB_header.setMaximumSize(QtCore.QSize(16777215, 75))
        self.LB_header.setText("")
        self.LB_header.setObjectName("LB_header")
        self.gridLayout_4.addWidget(self.LB_header, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.TW_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_job.setSortingEnabled(True)
        self.TW_main.setTabText(self.TW_main.indexOf(self.QW_job), QtGui.QApplication.translate("MainWindow", "Jobs", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_node.setSortingEnabled(True)
        self.TW_main.setTabText(self.TW_main.indexOf(self.QW_node), QtGui.QApplication.translate("MainWindow", "Slaves", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_auto_refresh.setText(QtGui.QApplication.translate("MainWindow", "Auto Refresh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Update every", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "seconds", None, QtGui.QApplication.UnicodeUTF8))

