# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newJob.ui'
#
# Created: Sun Mar  6 21:46:22 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(887, 741)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_4 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.LB_header = QtGui.QLabel(Dialog)
        self.LB_header.setText("")
        self.LB_header.setObjectName("LB_header")
        self.verticalLayout_4.addWidget(self.LB_header)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.CB_job_type = QtGui.QComboBox(Dialog)
        self.CB_job_type.setMinimumSize(QtCore.QSize(0, 35))
        self.CB_job_type.setObjectName("CB_job_type")
        self.horizontalLayout_26.addWidget(self.CB_job_type)
        self.verticalLayout_4.addLayout(self.horizontalLayout_26)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.TB_information = QtGui.QWidget()
        self.TB_information.setObjectName("TB_information")
        self.gridLayout_2 = QtGui.QGridLayout(self.TB_information)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LY_information = QtGui.QVBoxLayout()
        self.LY_information.setObjectName("LY_information")
        self.gridLayout_2.addLayout(self.LY_information, 0, 0, 1, 1)
        self.tabWidget.addTab(self.TB_information, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_34.addWidget(self.label_32)
        self.SB_numcpus = QtGui.QSpinBox(self.tab_2)
        self.SB_numcpus.setObjectName("SB_numcpus")
        self.horizontalLayout_34.addWidget(self.SB_numcpus)
        self.gridLayout_3.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_35 = QtGui.QLabel(self.tab_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_37.addWidget(self.label_35)
        self.SB_numcpus_cmp = QtGui.QSpinBox(self.tab_2)
        self.SB_numcpus_cmp.setObjectName("SB_numcpus_cmp")
        self.horizontalLayout_37.addWidget(self.SB_numcpus_cmp)
        self.gridLayout_3.addLayout(self.horizontalLayout_37, 1, 0, 1, 1)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_36.addWidget(self.label_34)
        self.SB_min_mem = QtGui.QSpinBox(self.tab_2)
        self.SB_min_mem.setObjectName("SB_min_mem")
        self.horizontalLayout_36.addWidget(self.SB_min_mem)
        self.gridLayout_3.addLayout(self.horizontalLayout_36, 2, 0, 1, 1)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_35.addWidget(self.label_33)
        self.CB_render_pool = QtGui.QComboBox(self.tab_2)
        self.CB_render_pool.setEditable(True)
        self.CB_render_pool.setObjectName("CB_render_pool")
        self.CB_render_pool.addItem("")
        self.horizontalLayout_35.addWidget(self.CB_render_pool)
        self.gridLayout_3.addLayout(self.horizontalLayout_35, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.CK_irix = QtGui.QCheckBox(self.groupBox_3)
        self.CK_irix.setChecked(True)
        self.CK_irix.setObjectName("CK_irix")
        self.horizontalLayout_38.addWidget(self.CK_irix)
        self.CK_linux = QtGui.QCheckBox(self.groupBox_3)
        self.CK_linux.setChecked(True)
        self.CK_linux.setObjectName("CK_linux")
        self.horizontalLayout_38.addWidget(self.CK_linux)
        self.CK_osx = QtGui.QCheckBox(self.groupBox_3)
        self.CK_osx.setChecked(True)
        self.CK_osx.setObjectName("CK_osx")
        self.horizontalLayout_38.addWidget(self.CK_osx)
        self.CK_bsd = QtGui.QCheckBox(self.groupBox_3)
        self.CK_bsd.setChecked(True)
        self.CK_bsd.setObjectName("CK_bsd")
        self.horizontalLayout_38.addWidget(self.CK_bsd)
        self.CK_windows = QtGui.QCheckBox(self.groupBox_3)
        self.CK_windows.setChecked(True)
        self.CK_windows.setObjectName("CK_windows")
        self.horizontalLayout_38.addWidget(self.CK_windows)
        self.gridLayout_3.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.CK_module = QtGui.QCheckBox(self.groupBox_2)
        self.CK_module.setObjectName("CK_module")
        self.horizontalLayout_39.addWidget(self.CK_module)
        self.LE_module = QtGui.QLineEdit(self.groupBox_2)
        self.LE_module.setEnabled(False)
        self.LE_module.setObjectName("LE_module")
        self.horizontalLayout_39.addWidget(self.LE_module)
        self.verticalLayout_2.addLayout(self.horizontalLayout_39)
        self.TW_envs = QtGui.QTableWidget(self.groupBox_2)
        self.TW_envs.setObjectName("TW_envs")
        self.TW_envs.setColumnCount(2)
        self.TW_envs.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.TW_envs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TW_envs.setHorizontalHeaderItem(1, item)
        self.TW_envs.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_2.addWidget(self.TW_envs)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_12 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout.addWidget(self.checkBox_12)
        self.checkBox_13 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout.addWidget(self.checkBox_13)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout.addWidget(self.lineEdit_8)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.checkBox_14 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_41.addWidget(self.checkBox_14)
        self.comboBox_9 = QtGui.QComboBox(self.groupBox)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_41.addWidget(self.comboBox_9)
        self.verticalLayout.addLayout(self.horizontalLayout_41)
        self.checkBox_15 = QtGui.QCheckBox(self.groupBox)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout.addWidget(self.checkBox_15)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.PB_submit = QtGui.QPushButton(Dialog)
        self.PB_submit.setObjectName("PB_submit")
        self.horizontalLayout_19.addWidget(self.PB_submit)
        self.PB_submit_stopped = QtGui.QPushButton(Dialog)
        self.PB_submit_stopped.setObjectName("PB_submit_stopped")
        self.horizontalLayout_19.addWidget(self.PB_submit_stopped)
        self.PB_cancel = QtGui.QPushButton(Dialog)
        self.PB_cancel.setObjectName("PB_cancel")
        self.horizontalLayout_19.addWidget(self.PB_cancel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_19)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TB_information), QtGui.QApplication.translate("Dialog", "information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog", "Maximum Number Of Cpus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog", "Maximum Number Of Cpus on One computer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog", "Minimum ammount of Memory in MB ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "Render in Pool", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_render_pool.setItemText(0, QtGui.QApplication.translate("Dialog", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Operating Systems", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_irix.setText(QtGui.QApplication.translate("Dialog", "Irix", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_linux.setText(QtGui.QApplication.translate("Dialog", "Linux", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_osx.setText(QtGui.QApplication.translate("Dialog", "OS X", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_bsd.setText(QtGui.QApplication.translate("Dialog", "FreeBSD", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_windows.setText(QtGui.QApplication.translate("Dialog", "Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Environments", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_module.setText(QtGui.QApplication.translate("Dialog", "Load Module", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_envs.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_envs.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("Dialog", "Mail Notification", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("Dialog", "Specific Email", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("Dialog", "Job depends on Id (jobid)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("Dialog", "Delete Job When finished", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Flags", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_submit.setText(QtGui.QApplication.translate("Dialog", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_submit_stopped.setText(QtGui.QApplication.translate("Dialog", "Submit Stopped", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

