# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newJob.ui'
#
# Created: Mon Jan 31 13:28:40 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(887, 774)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.label_25 = QtGui.QLabel(Dialog)
        self.label_25.setStyleSheet("None")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_26.addWidget(self.label_25)
        self.CB_job_type = QtGui.QComboBox(Dialog)
        self.CB_job_type.setObjectName("CB_job_type")
        self.horizontalLayout_26.addWidget(self.CB_job_type)
        self.gridLayout.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.PB_submit = QtGui.QPushButton(Dialog)
        self.PB_submit.setObjectName("PB_submit")
        self.horizontalLayout_19.addWidget(self.PB_submit)
        self.PB_submit_stopped = QtGui.QPushButton(Dialog)
        self.PB_submit_stopped.setObjectName("PB_submit_stopped")
        self.horizontalLayout_19.addWidget(self.PB_submit_stopped)
        self.PB_cancel = QtGui.QPushButton(Dialog)
        self.PB_cancel.setObjectName("PB_cancel")
        self.horizontalLayout_19.addWidget(self.PB_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.TB_information = QtGui.QWidget()
        self.TB_information.setObjectName("TB_information")
        self.gridLayout_2 = QtGui.QGridLayout(self.TB_information)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_27 = QtGui.QLabel(self.TB_information)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)
        self.SB_padding = QtGui.QSpinBox(self.TB_information)
        self.SB_padding.setObjectName("SB_padding")
        self.horizontalLayout_28.addWidget(self.SB_padding)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_19 = QtGui.QLabel(self.TB_information)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_20.addWidget(self.label_19)
        self.LE_name = QtGui.QLineEdit(self.TB_information)
        self.LE_name.setMinimumSize(QtCore.QSize(0, 0))
        self.LE_name.setObjectName("LE_name")
        self.horizontalLayout_20.addWidget(self.LE_name)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 1, 0, 1, 1)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_20 = QtGui.QLabel(self.TB_information)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_21.addWidget(self.label_20)
        self.LE_command = QtGui.QLineEdit(self.TB_information)
        self.LE_command.setObjectName("LE_command")
        self.horizontalLayout_21.addWidget(self.LE_command)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 2, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtGui.QLabel(self.TB_information)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.SB_start_frame = QtGui.QSpinBox(self.TB_information)
        self.SB_start_frame.setObjectName("SB_start_frame")
        self.horizontalLayout_25.addWidget(self.SB_start_frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 3, 0, 1, 1)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_22 = QtGui.QLabel(self.TB_information)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_23.addWidget(self.label_22)
        self.SB_end_frame = QtGui.QSpinBox(self.TB_information)
        self.SB_end_frame.setObjectName("SB_end_frame")
        self.horizontalLayout_23.addWidget(self.SB_end_frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_23, 4, 0, 1, 1)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_21 = QtGui.QLabel(self.TB_information)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_22.addWidget(self.label_21)
        self.SB_step_frame = QtGui.QSpinBox(self.TB_information)
        self.SB_step_frame.setObjectName("SB_step_frame")
        self.horizontalLayout_22.addWidget(self.SB_step_frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_22, 5, 0, 1, 1)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_23 = QtGui.QLabel(self.TB_information)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_24.addWidget(self.label_23)
        self.SB_block_size = QtGui.QSpinBox(self.TB_information)
        self.SB_block_size.setObjectName("SB_block_size")
        self.horizontalLayout_24.addWidget(self.SB_block_size)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 6, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_26 = QtGui.QLabel(self.TB_information)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_27.addWidget(self.label_26)
        self.CB_priority = QtGui.QComboBox(self.TB_information)
        self.CB_priority.setObjectName("CB_priority")
        self.CB_priority.addItem("")
        self.CB_priority.addItem("")
        self.CB_priority.addItem("")
        self.CB_priority.addItem("")
        self.CB_priority.addItem("")
        self.CB_priority.addItem("")
        self.horizontalLayout_27.addWidget(self.CB_priority)
        self.SB_priority = QtGui.QSpinBox(self.TB_information)
        self.SB_priority.setObjectName("SB_priority")
        self.horizontalLayout_27.addWidget(self.SB_priority)
        self.gridLayout_2.addLayout(self.horizontalLayout_27, 7, 0, 1, 1)
        self.tabWidget.addTab(self.TB_information, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_32 = QtGui.QLabel(self.tab_2)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_34.addWidget(self.label_32)
        self.SB_numcpus = QtGui.QSpinBox(self.tab_2)
        self.SB_numcpus.setObjectName("SB_numcpus")
        self.horizontalLayout_34.addWidget(self.SB_numcpus)
        self.gridLayout_3.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.horizontalLayout_37 = QtGui.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_35 = QtGui.QLabel(self.tab_2)
        self.label_35.setObjectName("label_35")
        self.horizontalLayout_37.addWidget(self.label_35)
        self.SB_numcpus_cmp = QtGui.QSpinBox(self.tab_2)
        self.SB_numcpus_cmp.setObjectName("SB_numcpus_cmp")
        self.horizontalLayout_37.addWidget(self.SB_numcpus_cmp)
        self.gridLayout_3.addLayout(self.horizontalLayout_37, 1, 0, 1, 1)
        self.horizontalLayout_36 = QtGui.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_34 = QtGui.QLabel(self.tab_2)
        self.label_34.setObjectName("label_34")
        self.horizontalLayout_36.addWidget(self.label_34)
        self.SB_min_mem = QtGui.QSpinBox(self.tab_2)
        self.SB_min_mem.setObjectName("SB_min_mem")
        self.horizontalLayout_36.addWidget(self.SB_min_mem)
        self.gridLayout_3.addLayout(self.horizontalLayout_36, 2, 0, 1, 1)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label_33 = QtGui.QLabel(self.tab_2)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout_35.addWidget(self.label_33)
        self.CB_render_pool = QtGui.QComboBox(self.tab_2)
        self.CB_render_pool.setEditable(True)
        self.CB_render_pool.setObjectName("CB_render_pool")
        self.CB_render_pool.addItem("")
        self.horizontalLayout_35.addWidget(self.CB_render_pool)
        self.gridLayout_3.addLayout(self.horizontalLayout_35, 3, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_38 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.CK_irix = QtGui.QCheckBox(self.groupBox_3)
        self.CK_irix.setChecked(True)
        self.CK_irix.setObjectName("CK_irix")
        self.horizontalLayout_38.addWidget(self.CK_irix)
        self.CK_linux = QtGui.QCheckBox(self.groupBox_3)
        self.CK_linux.setChecked(True)
        self.CK_linux.setObjectName("CK_linux")
        self.horizontalLayout_38.addWidget(self.CK_linux)
        self.CK_osx = QtGui.QCheckBox(self.groupBox_3)
        self.CK_osx.setChecked(True)
        self.CK_osx.setObjectName("CK_osx")
        self.horizontalLayout_38.addWidget(self.CK_osx)
        self.CK_bsd = QtGui.QCheckBox(self.groupBox_3)
        self.CK_bsd.setChecked(True)
        self.CK_bsd.setObjectName("CK_bsd")
        self.horizontalLayout_38.addWidget(self.CK_bsd)
        self.CK_windows = QtGui.QCheckBox(self.groupBox_3)
        self.CK_windows.setChecked(True)
        self.CK_windows.setObjectName("CK_windows")
        self.horizontalLayout_38.addWidget(self.CK_windows)
        self.gridLayout_3.addWidget(self.groupBox_3, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_39 = QtGui.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.CK_module = QtGui.QCheckBox(self.tab)
        self.CK_module.setObjectName("CK_module")
        self.horizontalLayout_39.addWidget(self.CK_module)
        self.LE_module = QtGui.QLineEdit(self.tab)
        self.LE_module.setEnabled(False)
        self.LE_module.setObjectName("LE_module")
        self.horizontalLayout_39.addWidget(self.LE_module)
        self.gridLayout_4.addLayout(self.horizontalLayout_39, 0, 0, 1, 1)
        self.TW_envs = QtGui.QTableWidget(self.tab)
        self.TW_envs.setObjectName("TW_envs")
        self.TW_envs.setColumnCount(2)
        self.TW_envs.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.TW_envs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.TW_envs.setHorizontalHeaderItem(1, item)
        self.TW_envs.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_4.addWidget(self.TW_envs, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_40 = QtGui.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.checkBox_12 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_40.addWidget(self.checkBox_12)
        self.checkBox_13 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_40.addWidget(self.checkBox_13)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_40.addWidget(self.lineEdit_8)
        self.gridLayout_5.addLayout(self.horizontalLayout_40, 0, 0, 1, 1)
        self.horizontalLayout_41 = QtGui.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.checkBox_14 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_41.addWidget(self.checkBox_14)
        self.comboBox_9 = QtGui.QComboBox(self.tab_3)
        self.comboBox_9.setObjectName("comboBox_9")
        self.horizontalLayout_41.addWidget(self.comboBox_9)
        self.gridLayout_5.addLayout(self.horizontalLayout_41, 1, 0, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(self.tab_3)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_5.addWidget(self.checkBox_15, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("Dialog", "Job Type", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_submit.setText(QtGui.QApplication.translate("Dialog", "Submit", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_submit_stopped.setText(QtGui.QApplication.translate("Dialog", "Submit Stopped", None, QtGui.QApplication.UnicodeUTF8))
        self.PB_cancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Dialog", "Frame Padding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog", "Command", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog", "Step Frames", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog", "Block Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Dialog", "Priority", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_priority.setItemText(0, QtGui.QApplication.translate("Dialog", "Highest", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_priority.setItemText(1, QtGui.QApplication.translate("Dialog", "High", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_priority.setItemText(2, QtGui.QApplication.translate("Dialog", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_priority.setItemText(3, QtGui.QApplication.translate("Dialog", "Low", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_priority.setItemText(4, QtGui.QApplication.translate("Dialog", "Lowest", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_priority.setItemText(5, QtGui.QApplication.translate("Dialog", "Custom", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TB_information), QtGui.QApplication.translate("Dialog", "information", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Dialog", "Maximum Number Of Cpus", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("Dialog", "Maximum Number Of Cpus on One computer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Dialog", "Minimum ammount of Memory in MB ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Dialog", "Render in Pool", None, QtGui.QApplication.UnicodeUTF8))
        self.CB_render_pool.setItemText(0, QtGui.QApplication.translate("Dialog", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Operating Systems", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_irix.setText(QtGui.QApplication.translate("Dialog", "Irix", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_linux.setText(QtGui.QApplication.translate("Dialog", "Linux", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_osx.setText(QtGui.QApplication.translate("Dialog", "OS X", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_bsd.setText(QtGui.QApplication.translate("Dialog", "FreeBSD", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_windows.setText(QtGui.QApplication.translate("Dialog", "Windows", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Limits", None, QtGui.QApplication.UnicodeUTF8))
        self.CK_module.setText(QtGui.QApplication.translate("Dialog", "Load Module", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_envs.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.TW_envs.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Envs", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("Dialog", "Mail Notification", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("Dialog", "Specific Email", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("Dialog", "Job depends on Id (jobid)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("Dialog", "Delete Job When finished", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Dialog", "Flags", None, QtGui.QApplication.UnicodeUTF8))

